import bundled from "../data/mvp.json";
import type { MvpData } from "../types/mvp";

/**
 * The MVP dataset, bundled at build time.
 *
 * There is no runtime fetch. The data is regenerated by the daily GitHub
 * Action (.github/workflows/refresh.yml), which commits src/data/mvp.json and
 * triggers a rebuild — so "refreshing" means a new deploy, not a request.
 *
 * The previous version fetched /api/mvp.json on mount and on every window
 * focus. That endpoint is dev-server middleware; on static hosting it returns
 * index.html, res.json() throws, and the footer permanently read "last refresh
 * failed, showing previous data" next to a dead Refresh button.
 */
export function useMvpData(): { data: MvpData } {
  return { data: bundled as MvpData };
}
