/** Generated by scripts/generators/mvp/build_mvp.py — do not hand-edit mvp.json. */

/**
 * Cell states. Only `met` and `gap` are scored.
 *
 * `na` is the connector declaring the processor does not support the capability
 * at all (the macro's `not_supported` list, which raises a different runtime
 * error from `not_implemented`). It is not a gap — no amount of work closes it —
 * so it is excluded from the denominator rather than counted against the
 * connector.
 *
 * `unknown` is deliberate and distinct from `gap`: "the source does not say"
 * and "the source says no" are different facts. `alias` marks a rubric row that
 * duplicates another (the Relay rows), shown for fidelity to the sheet but
 * never scored.
 */
export type MvpCellState = "met" | "gap" | "na" | "unknown" | "alias";

export interface MvpCapability {
  /**
   * "proven" — a compiler-enforced declaration; the cell is a fact, and these
   * alone drive met/gaps/effort/pct.
   * "best-effort" — a real capability with no certain signal. Displayed because
   * it is useful, excluded from scoring so it cannot contaminate a provable number.
   */
  confidence: "proven" | "best-effort";
  id: string;
  label: string;
  /** Abbreviated header for the matrix column; full `label` stays in the tooltip. */
  short: string;
  description: string;
  weight: number;
  signal: Record<string, unknown>;
}

/** Secondary signal only — whether the probe could BUILD a request. Never scored. */
export interface MvpProbe {
  buildableFlows: number;
  probedFlows: number;
}

export interface MvpGitProvenance {
  path: string;
  branch: string;
  commit: string;
  committedAt?: string;
  dirty: boolean | null;
}

/** Connector-level tier. Independent of the per-capability cell states: a
 *  connector is credentialed or not, which says nothing about whether any one
 *  capability is implemented. */
export type MvpTier = "sandbox_tested" | "alpha" | "no_docs";

export interface MvpConnector {
  /**
   * Whether credentials exist for this connector, derived on the batch machine
   * from the slot's creds.json — key names only, never a value.
   *
   * Shape is not judged: a legacy `connector_account_details` entry holds real
   * working credentials and counts as "ready".
   */
  credsState: "ready" | "missing";

  name: string;
  tier: MvpTier;
  cells: Record<string, MvpCellState>;
  /** Implemented gRPC flows, extracted from Rust source. */
  flows: string[];
  probe: MvpProbe | null;
  met: number;
  gaps: number;
  /** Capabilities the processor does not support; excluded from `scored`. */
  na: number;
  /** met + gap — na, unknown and alias are excluded from the denominator. */
  scored: number;
  effort: number;
  pct: number;
}

export interface MvpData {
  generatedAt: string;
  source: string;
  provenance: MvpGitProvenance | null;
  capabilities: MvpCapability[];
  connectors: MvpConnector[];
}
