/** Generated by scripts/generators/mvp/build_mvp.py — do not hand-edit mvp.json. */

/**
 * Cell states. Only `met` and `gap` are scored.
 *
 * `na` is the connector declaring the processor does not support the capability
 * at all (the macro's `not_supported` list, which raises a different runtime
 * error from `not_implemented`). It is not a gap — no amount of work closes it —
 * so it is excluded from the denominator rather than counted against the
 * connector.
 *
 * `unknown` is deliberate and distinct from `gap`: "the source does not say"
 * and "the source says no" are different facts. `alias` marks a rubric row that
 * duplicates another (the Relay rows), shown for fidelity to the sheet but
 * never scored.
 */
export type MvpCellState = "met" | "gap" | "na" | "unknown" | "alias";

export interface MvpCapability {
  /**
   * "proven" — a compiler-enforced declaration; the cell is a fact, and these
   * alone drive met/gaps/effort/pct.
   * "best-effort" — a real capability with no certain signal. Displayed because
   * it is useful, excluded from scoring so it cannot contaminate a provable number.
   */
  confidence: "proven" | "best-effort";
  id: string;
  label: string;
  /** Abbreviated header for the matrix column; full `label` stays in the tooltip. */
  short: string;
  description: string;
  weight: number;
  signal: Record<string, unknown>;
}

/** Secondary signal only — whether the probe could BUILD a request. Never scored. */
export interface MvpProbe {
  buildableFlows: number;
  probedFlows: number;
}

export interface MvpGitProvenance {
  path: string;
  branch: string;
  commit: string;
  committedAt?: string;
  dirty: boolean | null;
}

/** Connector-level tier. Independent of the per-capability cell states: a
 *  connector is credentialed or not, which says nothing about whether any one
 *  capability is implemented. */
export type MvpTier = "sandbox_tested" | "alpha" | "no_docs";

export interface MvpConnector {
  /**
   * Whether credentials exist for this connector, derived on the batch machine
   * from the slot's creds.json — key names only, never a value.
   *
   * Shape is not judged: a legacy `connector_account_details` entry holds real
   * working credentials and counts as "ready".
   */
  credsState: "ready" | "missing";
  /**
   * Whether the VENDOR publishes API documentation. Hand-researched.
   *
   * NOT the `no_docs` tier: that is set when the field probe returns no
   * supported flow, so our own docs generator skips the connector. All three
   * no_docs connectors in fact have documentation.
   */
  docsState: "public" | "gated" | "none" | "unknown";
  docsUrl: string | null;
  /** Which merchant is waiting on this connector, where known. */
  merchant: string | null;

  name: string;
  tier: MvpTier;
  cells: Record<string, MvpCellState>;
  /** Implemented gRPC flows, extracted from Rust source. */
  flows: string[];
  probe: MvpProbe | null;
  met: number;
  gaps: number;
  /** Capabilities the processor does not support; excluded from `scored`. */
  na: number;
  /** met + gap — na, unknown and alias are excluded from the denominator. */
  scored: number;
  effort: number;
  pct: number;
}

export interface MvpData {
  pipeline?: PipelineConnector[];
  generatedAt: string;
  source: string;
  provenance: MvpGitProvenance | null;
  capabilities: MvpCapability[];
  connectors: MvpConnector[];
}


/**
 * A connector in the business pipeline with no module in prism yet.
 *
 * Separate from MvpConnector because it has no cells, flows or score — there is
 * no Rust source to derive them from. Identified in the database by
 * refreshed_at IS NULL, since catalog_refresh.py only touches what it finds in
 * the source tree.
 */
export interface PipelineConnector {
  name: string;
  notes: string | null;
  docsState: "public" | "gated" | "none" | "unknown";
  docsUrl: string | null;
  credsState: "ready" | "missing";
  inQueue: boolean;
  merchant: string | null;
}
