/** Generated by scripts/generators/mvp/build_mvp.py — do not hand-edit mvp.json. */

/**
 * Cell states. Only `met` and `gap` are scored.
 *
 * `unknown` is deliberate and distinct from `gap`: "the source does not say"
 * and "the source says no" are different facts. `alias` marks a rubric row that
 * duplicates another (the Relay rows), shown for fidelity to the sheet but
 * never scored.
 */
export type MvpCellState = "met" | "gap" | "unknown" | "alias";

export interface MvpCapability {
  /**
   * "proven" — a compiler-enforced declaration; the cell is a fact, and these
   * alone drive met/gaps/effort/pct.
   * "best-effort" — a real capability with no certain signal. Displayed because
   * it is useful, excluded from scoring so it cannot contaminate a provable number.
   */
  confidence: "proven" | "best-effort";
  id: string;
  label: string;
  description: string;
  weight: number;
  signal: Record<string, unknown>;
}

/** Secondary signal only — whether the probe could BUILD a request. Never scored. */
export interface MvpProbe {
  buildableFlows: number;
  probedFlows: number;
}

export interface MvpGitProvenance {
  path: string;
  branch: string;
  commit: string;
  committedAt?: string;
  dirty: boolean | null;
}

export interface MvpConnector {
  name: string;
  cells: Record<string, MvpCellState>;
  /** Implemented gRPC flows, extracted from Rust source. */
  flows: string[];
  probe: MvpProbe | null;
  met: number;
  gaps: number;
  /** met + gap — unknown and alias are excluded from the denominator. */
  scored: number;
  effort: number;
  pct: number;
}

export interface MvpData {
  generatedAt: string;
  source: string;
  provenance: MvpGitProvenance | null;
  capabilities: MvpCapability[];
  connectors: MvpConnector[];
}
